kibot:
  version: 1

preflight:
  run_erc: false
  run_drc: false

outputs:

  # Design Docs

  - name: 'print_sch'
    comment: 'Print schematic (PDF)'
    type: pdf_sch_print
    dir: design

  - name: "download_ds"
    comment: "Download Datasheets"
    type: download_datasheets
    dir: design/datasheets

  - name: 'design_docs'
    comment: "Design Documentation"
    type: compress
    dir: .
    options:
      files:
        - {from_output: print_sch, dest: /}
        - {from_output: print_sch_svg, dest: /}
        - {from_output: download_ds, dest: /datasheets}

  # Renders
  - name: 'print_sch_svg'
    comment: "Print schematic (SVG)"
    type: svg_sch_print
    dir: renders

  - name: pcbdraw_top
    comment: "PcbDraw test top"
    type: pcbdraw
    dir: renders
    options: &pcb_draw_ops
      format: png
      no_drillholes: False
      placeholder: True
      mirror: False
      vcuts: True
      warnings: all
      show_components: all

  - name: pcbdraw_bottom
    comment: "PcbDraw test bottom"
    type: pcbdraw
    dir: renders
    options:
      <<: *pcb_draw_ops
      bottom: True

  # Misc.

  - name: 'ibom'
    comment: 'Interactive BOM'
    type: ibom
    dir: html
    options:
      dark_mode: false

  - name: "render3d"
    type: render_3d
    dir: renders
    options:
      rotate_x: 3
      rotate_z: -2

  - name: step
    comment: "Generate 3D model (STEP)"
    type: step
    dir: 3d
    options:
      metric_units: true
      origin: 85,66.2
